import { useState } from 'react'
import { Link } from 'react-router-dom'
import { BookOpen, Search, ArrowLeft, X } from 'lucide-react'

const TERMS = [
  { term: 'SHA-256', def: 'A cryptographic hash function that produces a 256-bit (64 character) hexadecimal fingerprint. Used by Satohash to create a unique identifier for each document without exposing its contents.' },
  { term: 'OpenTimestamps (OTS)', def: 'A protocol that creates timestamp proofs by embedding document hashes into Merkle trees, which are then anchored to the Bitcoin blockchain via a single transaction.' },
  { term: 'Merkle Tree', def: 'A data structure where each leaf node is a hash and each non-leaf node is the hash of its children. OTS aggregates many timestamps into one Merkle tree before anchoring to Bitcoin.' },
  { term: 'OTS File (.ots)', def: 'The proof file generated by Satohash containing the timestamp information. It is useless without the original document but can be verified independently using the open-source ots tool.' },
  { term: 'Bitcoin Blockchain', def: 'A decentralized, immutable public ledger maintained by a global network of miners. Satohash anchors proof fingerprints into Bitcoin blocks for permanent timestamping.' },
  { term: 'Block Height', def: 'The sequential number of a block in the Bitcoin blockchain. Each new block is assigned height + 1. The block height at the time of timestamping provides temporal proof.' },
  { term: 'NIP-05', def: 'Nostr Improvement Proposal #05 — maps a human-readable identifier (like user@domain.com) to a Nostr public key, enabling verifiable identity without sharing raw public keys.' },
  { term: 'Nostr', def: 'A decentralized, censorship-resistant protocol for social networking and communication. Used by Satohash for identity verification and agent communication.' },
  { term: 'BOLT-12', def: 'A Lightning Network proposal for reusable, one-click offers. Enables recurring payments and metered access without repeated invoice generation.' },
  { term: 'Lightning Network', def: 'A second-layer payment protocol on top of Bitcoin enabling instant, low-fee transactions. Used by Satohash for premium billing.' },
  { term: 'Zero-Knowledge Proof', def: 'A method to prove knowledge of information without revealing the information itself. In Satohash, your documents never leave your device — only their hashes are shared.' },
  { term: 'FOSS', def: 'Free and Open Source Software. Satohash is MIT-licensed and the full source code is publicly available on GitHub.' },
  { term: 'eIDAS', def: 'Electronic Identification, Authentication and Trust Services — an EU regulation that sets standards for electronic signatures and timestamping. Satohash proofs are eIDAS-compatible.' },
  { term: 'ESIGN Act', def: 'The United States federal law that establishes the legal validity of electronic signatures and records. Satohash proofs comply with ESIGN requirements.' },
  { term: 'Block Time', def: 'The average time between Bitcoin blocks (approximately 10 minutes). The timestamp of the block containing your proof determines the notarization time.' },
  { term: 'Mempool', def: 'The pool of unconfirmed Bitcoin transactions waiting to be included in a block. Satohash monitors the mempool for real-time network intelligence.' },
  { term: 'L402', def: 'A protocol standard for API authentication and metering using the Lightning Network. Enables pay-per-use access to premium features.' },
  { term: 'PWA', def: 'Progressive Web App — a web application that can be installed on a device and work offline. Satohash is a PWA with service worker caching.' }
]

export default function Glossary() {
  usePageMeta({
    title: 'Glossary — Satohash',
    description: 'Key terms explained: SHA-256, OpenTimestamps, Merkle Trees, NIP-05, BOLT-12, Zero-Knowledge Proofs and more.'
  })

  const [search, setSearch] = useState('')

  const filtered = TERMS.filter(t =>
    !search || t.term.toLowerCase().includes(search.toLowerCase()) ||
    t.def.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div className="min-h-screen bg-[var(--bg-primary)]">
      <header className="border-b border-[var(--border)] bg-[var(--bg-navbar)]/95 px-6 py-4 backdrop-blur-md">
        <div className="mx-auto flex max-w-4xl items-center gap-4">
          <Link to="/" className="flex min-h-[44px] items-center gap-2 text-sm font-bold text-[var(--text-secondary)] hover:text-[var(--accent-gold)]">
            <ArrowLeft size={16} /> Home
          </Link>
        </div>
      </header>

      <section className="border-b border-[var(--border)] px-6 pt-20 pb-16">
        <div className="mx-auto max-w-3xl text-center">
          <BookOpen size={28} className="mx-auto mb-4 text-[var(--accent-gold)]" />
          <h1 className="mb-4 text-4xl font-black tracking-tight text-[var(--text-primary)] sm:text-5xl">
            <span className="text-[var(--accent-gold)]">Glossary</span> of Terms
          </h1>
          <p className="mx-auto mb-8 max-w-xl text-sm leading-relaxed text-[var(--text-secondary)]">
            Key concepts explained simply. From SHA-256 to Zero-Knowledge Proofs.
          </p>
          <div className="relative mx-auto max-w-md">
            <Search size={16} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[var(--text-tertiary)]" />
            <input
              type="text"
              placeholder="Search terms..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="w-full min-h-[48px] rounded-xl border border-[var(--border)] bg-[var(--bg-primary)] pl-11 pr-4 text-sm text-[var(--text-primary)] placeholder-[var(--text-tertiary)] outline-none transition-colors focus:border-[var(--accent-gold)]"
            />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-6 py-16">
        {filtered.length === 0 ? (
          <div className="py-20 text-center">
            <p className="text-lg font-bold text-[var(--text-primary)]">No terms found</p>
            <p className="text-sm text-[var(--text-secondary)]">Try a different search.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {filtered.map((item, i) => (
              <div key={i} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-raised)] p-5 transition-all hover:border-[var(--accent-gold)]">
                <h3 className="mb-2 font-mono text-sm font-bold text-[var(--accent-gold)]">{item.term}</h3>
                <p className="text-xs leading-relaxed text-[var(--text-secondary)]">{item.def}</p>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  )
}
