import { jsPDF } from 'jspdf'

/**
 * Generate and download a PDF certificate of blockchain notarization.
 * @param {{ id: string, name: string, fullHash: string, hash: string, date: string, status: string }} item
 */
export function downloadCertificate(item) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = 210,
    margin = 20

  // Background
  doc.setFillColor(253, 251, 247)
  doc.rect(0, 0, pageW, 297, 'F')

  // Gold top bar
  doc.setFillColor(240, 180, 41)
  doc.rect(0, 0, pageW, 6, 'F')

  const isPending = (item.status || 'pending') !== 'confirmed'
  doc.setTextColor(220, 220, 220)
  doc.setFontSize(isPending ? 40 : 60)
  doc.setFont('helvetica', 'bold')
  doc.text(isPending ? 'PENDING OTS' : 'SATOHASH', 105, 160, { align: 'center', angle: 45 })

  // Title
  doc.setTextColor(15, 23, 42)
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text('CERTIFICATE OF', margin, 40)
  doc.text('BLOCKCHAIN NOTARIZATION', margin, 52)

  // Gold line
  doc.setDrawColor(240, 180, 41)
  doc.setLineWidth(1)
  doc.line(margin, 58, pageW - margin, 58)

  const fields = [
    ['Document', item.name],
    ['SHA-256 Hash', item.fullHash || item.hash],
    ['Proof ID', item.id],
    ['Date Notarized', item.date],
    ['Status', (item.status || 'pending').toUpperCase()],
    ['Protocol', 'OpenTimestamps / Bitcoin Mainnet'],
    ['Verification', `${window.location.origin}/verify`]
  ]

  let y = 75
  fields.forEach(([label, value]) => {
    doc.setFontSize(8)
    doc.setTextColor(120, 130, 150)
    doc.setFont('helvetica', 'bold')
    doc.text(label.toUpperCase(), margin, y)
    doc.setFontSize(11)
    doc.setTextColor(15, 23, 42)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(String(value), pageW - margin * 2)
    doc.text(lines, margin, y + 6)
    y += lines.length * 6 + 12
  })

  // Footer
  doc.setDrawColor(240, 180, 41)
  doc.setLineWidth(0.5)
  doc.line(margin, 270, pageW - margin, 270)
  doc.setFontSize(8)
  doc.setTextColor(150, 163, 175)
  doc.text('Generated by Satohash — Bitcoin-Anchored Document Notarization', margin, 278)
  doc.text(window.location.hostname, pageW - margin, 278, { align: 'right' })

  doc.save(`Satohash_Certificate_${item.id?.substring(0, 8) || 'proof'}.pdf`)
}
