import jsPDF from 'jspdf';

/**
 * Generate a proof package PDF with contract content and timestamp details
 */
export const generateProofPackage = (contract, timestamp) => {
    const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4'
    });

    const addPremiumBackground = (pdf) => {
        // Premium paper color (#fdfdfb)
        pdf.setFillColor(253, 253, 251);
        pdf.rect(0, 0, 210, 297, 'F');

        // Subtle Hash Watermark
        pdf.setTextColor(230, 230, 230);
        pdf.setFontSize(6);
        pdf.setFont('courier', 'normal');
        const hashStr = "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f ";
        for (let i = 0; i < 300; i += 30) {
            for (let j = -20; j < 230; j += 60) {
                pdf.text(hashStr.substring(0, 48), j, i, { angle: -30 });
            }
        }
    };

    const addDigitalSeal = (pdf, x, y) => {
        // Draw a "Wax Seal" style element
        pdf.setDrawColor(99, 102, 241);
        pdf.setFillColor(99, 102, 241);
        pdf.circle(x, y, 15, 'F');

        pdf.setDrawColor(255, 255, 255);
        pdf.setLineWidth(0.5);
        pdf.circle(x, y, 13, 'S');

        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(6);
        pdf.setFont('helvetica', 'bold');
        pdf.text('BITCOIN', x, y - 2, { align: 'center' });
        pdf.text('VERIFIED', x, y + 3, { align: 'center' });
    };

    // --- Page 1: Main Document ---
    addPremiumBackground(doc);

    // Official Logo Header
    try {
        doc.addImage('https://giveabit.io/wp-content/uploads/2022/04/sats_new.png', 'PNG', 95, 10, 20, 20);
    } catch (e) {
        console.error("Could not add logo to PDF:", e);
    }

    // Header
    doc.setTextColor(17, 24, 39);
    doc.setFont('times', 'bold');
    doc.setFontSize(24);
    doc.text((contract.name || 'Untitled Document').toUpperCase(), 105, 45, { align: 'center' });

    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(1.2);
    doc.line(40, 50, 170, 50);

    doc.setFontSize(9);
    doc.setFont('times', 'bold');
    doc.setTextColor(99, 102, 241);
    doc.text('BITCOIN PROOF OF EXISTENCE • SECURED BY SATOHASH', 105, 57, { align: 'center' });

    // Main Content
    doc.setTextColor(55, 65, 81);
    doc.setFont('times', 'normal');
    doc.setFontSize(11);
    const contentLines = doc.splitTextToSize(contract.content || '', 150);
    doc.text(contentLines, 30, 75, { align: 'justify', lineHeightFactor: 1.5 });

    // Add Seal if timestamped
    if (timestamp && timestamp.status === 'timestamped') {
        addDigitalSeal(doc, 170, 260);
    }

    // --- Page 2: Proof Details ---
    doc.addPage();
    addPremiumBackground(doc);

    doc.setTextColor(31, 41, 55);
    doc.setFont('times', 'bold');
    doc.setFontSize(18);
    doc.text('Cryptographic Proof of Existence', 20, 30);

    doc.setFont('times', 'normal');
    doc.setFontSize(10);
    doc.text(`Document Hash (SHA-256):`, 20, 45);
    doc.setFont('courier', 'bold');
    doc.text(timestamp ? timestamp.hash : 'N/A', 20, 52);

    doc.setFont('times', 'normal');
    doc.text(`Timestamp ID: ${contract.id}`, 20, 65);
    doc.text(`Anchored on: ${timestamp ? new Date(timestamp.createdAt).toLocaleString() : 'N/A'}`, 20, 72);
    doc.text(`Network: Bitcoin Blockchain (via OpenTimestamps)`, 20, 79);

    // Instructions
    doc.setFont('times', 'bold');
    doc.setFontSize(14);
    doc.text('Verification Instructions', 20, 100);

    doc.setFont('times', 'normal');
    doc.setFontSize(10);
    const instructions = [
        '1. Drag & drop this PDF into satohash.com/verify',
        '2. Or use independent tools at opentimestamps.org',
        '3. This proof is immutable and globally verifiable forever.',
        '',
        'Note: The .ots file provided in the proof package is the primary',
        'cryptographic evidence. This PDF is a human-readable summary.'
    ];
    doc.text(instructions, 20, 110);

    // Page 3: Legal Disclaimer
    doc.addPage();
    addPremiumBackground(doc);
    doc.setFont('times', 'bold');
    doc.setFontSize(14);
    doc.text('Legal Disclaimer', 20, 30);

    doc.setFont('times', 'normal');
    doc.setFontSize(10);
    const disclaimer = doc.splitTextToSize(
        'This cryptographic proof package is generated by Satohash using OpenTimestamps, an open standard for blockchain timestamping. ' +
        'Satohash is a tool for creating cryptographic evidence that a document existed at a specific time. ' +
        'Satohash does not provide legal advice and makes no guarantees about the legal enforceability of this proof. ' +
        'The legal validity of timestamped documents varies by jurisdiction. Consult with a qualified attorney in your ' +
        'jurisdiction for legal advice.',
        170
    );
    doc.text(disclaimer, 20, 42);

    return doc;
};

/**
 * Download the PDF proof package
 */
export const downloadProofPackage = (contract, timestamp) => {
    const doc = generateProofPackage(contract, timestamp);
    doc.save(`${contract.name}_proof_${Date.now()}.pdf`);
};

/**
 * Generate and download the .ots file
 */
export const downloadOTSFile = (timestamp) => {
    const blob = new Blob([timestamp.otsData], { type: 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `proof_${Date.now()}.ots`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
